[package]
name = "auto_css_modules"
version = "1.1.0"
authors = ["fz6m"]
description = "Auto css modules plugin for swc"
edition = "2021"
license = "MIT"
repository = "https://github.com/xn-sakina/swc-plugin-auto-css-modules.git"
publish = false

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
swc_core = { version = "0.48.29", features = [
  "ecma_visit",
  "ecma_ast",
] }

[dev-dependencies]
serde_json = "1.0.79"
swc_core = { features = [
  "ecma_parser",
  "ecma_transforms",
  "testing_transform",
  "common",
], version = "0.48.29" }
testing = "0.31.25"
